GamePlay.create!([
  {user_id: 1, score: 10, level: 1},
  {user_id: 1, score: 17, level: 1},
  {user_id: 1, score: 13, level: 1},
  {user_id: 1, score: 17, level: 1},
  {user_id: 1, score: 17, level: 1},
  {user_id: 1, score: 13, level: 1},
  {user_id: 1, score: 10, level: 1},
  {user_id: 1, score: 13, level: 1},
  {user_id: 1, score: 10, level: 1},
  {user_id: 1, score: 13, level: 1},
  {user_id: 1, score: 10, level: 1},
  {user_id: 4, score: 6, level: 1},
  {user_id: 4, score: 2, level: 1},
  {user_id: 4, score: 24, level: 1},
  {user_id: 4, score: 6, level: 1},
  {user_id: 4, score: 24, level: 1},
  {user_id: 2, score: 6, level: 1},
  {user_id: 4, score: 62, level: 1},
  {user_id: 4, score: 10, level: 1},
  {user_id: 7, score: 38, level: 1},
  {user_id: 3, score: 50, level: 1},
  {user_id: 3, score: 18, level: 1},
  {user_id: 3, score: 2, level: 1},
  {user_id: 3, score: 8, level: 1},
  {user_id: 3, score: 10, level: 1},
  {user_id: 3, score: 6, level: 1},
  {user_id: 3, score: 4, level: 1},
  {user_id: 3, score: 2, level: 1},
  {user_id: 3, score: 8, level: 1},
  {user_id: 3, score: 78, level: 1},
  {user_id: 3, score: 22, level: 1},
  {user_id: 3, score: 50, level: 1},
  {user_id: 4, score: 4, level: 1},
  {user_id: 4, score: 6, level: 1},
  {user_id: 4, score: 28, level: 1},
  {user_id: 4, score: 23, level: 1},
  {user_id: 4, score: 112, level: 1},
  {user_id: 5, score: 18, level: 1},
  {user_id: 5, score: 49, level: 6},
  {user_id: 5, score: 32, level: 5},
  {user_id: 5, score: 9, level: 2},
  {user_id: 5, score: 220, level: 4},
  {user_id: 5, score: 67, level: 6},
  {user_id: 4, score: 65, level: 3},
  {user_id: 3, score: 63, level: 2},
  {user_id: 3, score: 22, level: 1},
  {user_id: 3, score: 51, level: 2},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 3, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: -2, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: -2, level: 1},
  {user_id: 3, score: -4, level: 1},
  {user_id: 3, score: -6, level: 1},
  {user_id: 3, score: -10, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: -2, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: -2, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: -2, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: -2, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: -1, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 44, level: 2},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: -1, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 0, level: 1},
  {user_id: 3, score: 35, level: 4},
  {user_id: 3, score: 74, level: 3},
  {user_id: 5, score: 30, level: 2}
])
User.create!([
  {username: "johnnysockets", name: "Johnathon Sockets", city: "Phoenix", state: "Arizona", mini_bio: "Middle School Student. Likes the desert. Wants to up his game in English class.", age: 12},
  {username: "sammysmiles", name: "Samantha Sunshine", city: "San Diego", state: "California ", mini_bio: "Grammar Queen. Likes games, running and tennis. Smiles FOR DAYS.", age: 11},
  {username: "dearjournal", name: "Doug Funny", city: "Bluffington", state: "Washington", mini_bio: "I love writng in my journal. It helps me reflect on my day to day issues. I hope to improve my writing with a little extra grammar practice.", age: 11},
  {username: "schoolrules", name: "Lisa Simpson", city: "Springfield", state: "Illinois", mini_bio: "Third grader. I love school, studying and learning. I am at the top of my class. I fight with my brother", age: 8},
  {username: "sleuthmaster", name: "Velma Dinkley", city: "Coolsville", state: "Ohio", mini_bio: "High School student. Validictorian of my class. Really good at solving mysteries. Grammar is my second love. Jinkies!", age: 15},
  {username: "atleastitried", name: "Charlie Brown", city: "Minneapolis", state: "Minnesota", mini_bio: "I'm not very good at grammar, or games, or winning, but at least I tried, right?", age: 8},
  {username: "notspiderman", name: "Peter Parker", city: "Forest Hills", state: "New York", mini_bio: "In my free time, I might fight crime, but that's a secret. You're not supposed to know. I like to consider myself a friendly neighborhood helper. Grammar is not a priority, but Aunt May wants me to try harder. So, here I am.", age: 13},
  {username: "siiiighhh", name: "Daria Morgendorffer", city: "Lawndale", state: "Texas", mini_bio: "I don't really like grammar. I don't really like games. Nothing matters. This is all an illusion. I hate smiling.", age: 16},
  {username: "wonderwoman", name: "Diana Prince", city: "Paris", state: "Illinois", mini_bio: "I am awesome, because I am Wonder Woman.", age: 22}
])
Word.create!([
  {content: "a", noun: false, verb: false, adjective: false, pronoun: false, preposition: false, article: true, conjunction: false, adverb: false},
  {content: "cat", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "smelly", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "sleeps", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "dog", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "squishy", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "trots", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "horse", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "wimpers", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "handsome", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "kangaroo", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "hops", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "young", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "sharp", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "student", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "succeeds", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "pretty", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "girl", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "dances", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "sharp", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "student", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "wins", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "sad", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "clown", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "cries", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "slimy", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "fish", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "swims", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "large", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "bear", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "green", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "dinosaur", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "eats", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "fly", noun: true, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "sister", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "fluffy", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "write", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "lion", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "break", noun: true, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "cloudy", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "biscuit", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "waves", noun: true, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "terrific", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "energetic", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "sushi roll", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "chews", noun: false, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "spiky", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "cactus", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "chops", noun: true, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "ripe", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "hamster", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "win", noun: true, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "wooden", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "pizza", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "laugh", noun: true, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "clever", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "sweater", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "scribbles", noun: true, verb: true, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "witty", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "brother", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "river", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "bright", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "dime", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "she", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "he", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "it", noun: true, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "I", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "you", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "we", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "me", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "they", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "him", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "her", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "us", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "them", noun: true, verb: false, adjective: false, pronoun: true, preposition: false, article: false, conjunction: false, adverb: false},
  {content: "an", noun: false, verb: false, adjective: false, pronoun: false, preposition: false, article: true, conjunction: false, adverb: false},
  {content: "the", noun: false, verb: false, adjective: false, pronoun: false, preposition: false, article: true, conjunction: false, adverb: false},
  {content: "with", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "at", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "from", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "into", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "during", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "including", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "against", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "among", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "towards", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "upon", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: false, adverb: false},
  {content: "for", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: true, adverb: false},
  {content: "yet", noun: false, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: true, adverb: true},
  {content: "after", noun: false, verb: false, adjective: true, pronoun: false, preposition: false, article: false, conjunction: true, adverb: false},
  {content: "although", noun: false, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: true, adverb: false},
  {content: "because", noun: false, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: true, adverb: false},
  {content: "for", noun: false, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: true, adverb: false},
  {content: "before", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: true, adverb: true},
  {content: "once", noun: false, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: true, adverb: true},
  {content: "since", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: true, adverb: true},
  {content: "though", noun: false, verb: false, adjective: false, pronoun: false, preposition: false, article: false, conjunction: true, adverb: true},
  {content: "as", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: true, adverb: false},
  {content: "till", noun: false, verb: false, adjective: false, pronoun: false, preposition: true, article: false, conjunction: true, adverb: false}
])
